### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by RED4911** [Totenfluch/SmartLinkRemover#10]
L 04/17/2017 - 21:49:25: SourceMod error session started
L 04/17/2017 - 21:49:25: Info (map "de_dust2") (file "errors_20170417.log")
L 04/17/2017 - 21:49:25: [SM] Exception reported: Client 2 is not connected
L 04/17/2017 - 21:49:25: [SM] Blaming: SmartLinkRemover.smx
L 04/17/2017 - 21:49:25: [SM] Call stack trace:
L 04/17/2017 - 21:49:25: [SM]   [0] SetClientName
L 04/17/2017 - 21:49:25: [SM]   [1] Line 90, C:\Users\Desktop\sourcemod\scripting\SmartLinkRemover.sp::delayedNameChange

**Comment by Totenfluch** [comment]
Fixed with #11
