### ISSUE TITLE
Prevent users name from being 'URL Removed'

### ISSUE THREAD

**Issue by MitchDizzle** [Totenfluch/SmartLinkRemover#12]
Perhaps we can make it so instead of a user's name being "URL Removed" we can just strip off the extension. So if a player's name is "mtch.tech" it becomes "mtch".

**Comment by Totenfluch** [comment]
If someone is called csgojackpot.com or smth. I don't want them to be named csgojackpot

**Comment by MitchDizzle** [comment]
I've added it as a ConVar (default on, however this can change).
I guess this was just to prevent people who have their own domain being changed to "URL Removed"
