### ISSUE TITLE
Not found link these name

### ISSUE THREAD

**Issue by Deniel00** [Totenfluch/SmartLinkRemover#16]
Hi!

The regex can't see the link this name: .#gamdom.comNok1
Can you upgrade your regex?

**Comment by Totenfluch** [comment]
You are basically asking to detect anything that has a dot in between the name
I could add that it doesn't detect if after the domain there is a capital letter but that would be easily bypassed by "gamdom.COMNok1"

If you have a very smart Idea on how to fix this I'm happy to get some input from you
