### ISSUE TITLE
Regex don't find the link

### ISSUE THREAD

**Issue by Bara** [Totenfluch/SmartLinkRemover#17]
❌-__ Σχεcυтισи__-❌ cs.money

https://regex101.com/ says: Your regular expression does not match the subject string.

When you try just "cs.money" it doesn't work too.

**Comment by Totenfluch** [comment]
can't replicate this.
Did you select Javascript?

https://imgur.com/yI96oYG

**Comment by Bara** [comment]
Not seen anymore
