### ISSUE TITLE
BUG Links Allowed

### ISSUE THREAD

**Issue by crashzk** [Totenfluch/SmartLinkRemover#20]
I found a BUG.

I downloaded the latest version here: https://github.com/Totenfluch/SmartLinkRemover

It even locks the links if someone tries to join the server.

But I configured link allowed in the SmartLink_whitelist.cfg config and even then it will not, when the player enters the plugin it changes his nick.

@Totenfluch

**Comment by Totenfluch** [comment]
can you post your config?

**Comment by crashzk** [comment]
The following is the config:
```
"SmartLinkRemover Whitelist"
{
//  "URL"  "FLAGS"
//  "google.com"  ""
//  "my.clan"  "b"
//  "site.com"  "opqr"
	"zkservidores.com"	""
	"twitch.tv/tunezcs"	""
	"twitch.tv/dyuu"	""
}
```

**Comment by Totenfluch** [comment]
what do you mean by "lock the links" ?

**Comment by crashzk** [comment]
In case I wanted to set up some links, I would be allowed to use them.

**Then I put these links in the config:**
```
"SmartLinkRemover Whitelist"
{
//  "URL"  "FLAGS"
//  "google.com"  ""
//  "my.clan"  "b"
//  "site.com"  "opqr"
	"zkservidores.com"	""
	"twitch.tv/tunezcs"	""
	"twitch.tv/dyuu"	""
}
```
That is the players that entered with some of these link in the nick could have it, but it does not happen, the nick changes to the nick **"URL Removed"**.

How can I make such links allowed on my servers?

**Comment by Totenfluch** [comment]
The whitelist is confirmed to be working.

I think we might have another problem here... can you confirm for me that the "zkservidores.com" Link whitelist works (or deny that it doesn't) ?

**Comment by crashzk** [comment]
The link **"zkservidores.com"** apparently yes, I enter and nothing happens, I do not know if it has anything to do with having root access on the servers.

Now the other link does not, when any player enters the server using them from the **"URL Removed"**.

**Comment by Totenfluch** [comment]
I think it's about the /xxxx from twitch.tv since the regex only capures the twitch.tv and not the directory after it...

**Comment by crashzk** [comment]
I'll be testing and returning with the result...

**Comment by Totenfluch** [comment]
did you find something out or is the plugin working as intended and this can be closed?

**Comment by crashzk** [comment]
So far no problem, no more players came with twitch.tv link.

Any problem return the contact, thanks for now!
