### ISSUE TITLE
[Feature Request] Update link detection mode

### ISSUE THREAD

**Issue by crashzk** [Totenfluch/SmartLinkRemover#22]
I do not believe it is a BUG, ​​in any case players can bypass the plugin if they put **","** in the links instead of the **"."**.

Here's a print: http://prntscr.com/mvxbrt

Would I have some way to correct that?

**Comment by Totenfluch** [comment]
we could add "," into the regex, however this may produce unintentional side effects... maybe as a config option?

**Comment by crashzk** [comment]
It could be, in case just blocking for me this perfect.

**Comment by Totenfluch** [comment]
`([ ]*[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[:0-9]{0,6})|([ ]*(http:[/]{2}|https:[/]{2}|www[.])?([-a-zA-Z0-9]{2,}[.,][a-zA-Z]{2,5})([a-zA-Z0-9]*?[.][a-zA-Z0-9]{2,5})?([/][a-zA-Z0-9]*)*(?=[^a-zA-Z0-9]|$))`

use this regex and recompile
I recommend banning the players for some minutes that try to get around the removal tho

**Comment by Totenfluch** [comment]
![image](https://user-images.githubusercontent.com/1492431/54088880-edfabf80-4362-11e9-825a-9325d555cdbc.png)

**Comment by crashzk** [comment]
Perfect, I'll be testing and returning with the result.

Taking advantage of the hook, not if already already seen, however the option of WhiteList does not work, even the player having privileges he can not put links.

**Comment by crashzk** [comment]
```
([ ]*[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}[:0-9]{0,6})|([ ]*(http:[/]{2}|https:[/]{2}|www[.])?([-a-zA-Z0-9]{2,}[.,][a-zA-Z]{2,5})([a-zA-Z0-9]*?[.][a-zA-Z0-9]{2,5})?([/][a-zA-Z0-9]*)*(?=[^a-zA-Z0-9]|$))

use this regex and recompile
I recommend banning the players for some minutes that try to get around the removal tho
```
I did the test with these modifications and so far no problems, I find it interesting to put in future updates of the plugin.

@Totenfluch
