### ISSUE TITLE
[Any][MySQL] tVip (2.2 | 05-03-19) - The simplest to use Vip Manager

### ISSUE THREAD

**Issue by ghost** [Totenfluch/SmartLinkRemover#27]
I am having the following problem:

In admin.ini I have:

"Steamid" "qa"

On tVip cfg (Located in cfg / soucemod)
How do I when I add someone in VIP to have these two Flags? Because I in tVip cfg I have the following:

tVip_flag "0 17"

Where 0 corresponds to -> ADMFLAG_RESERVATION (a)

And where the 17 corresponds to -> ADMFLAG_CUSTOM3 (q)

However, when I add someone to VIP the person is only getting the flag "a", and the flag "q" or "17" is not working !!!

**Comment by Totenfluch** [comment]
Wrong repository. Use the thread.
